package com.admin.web.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("job_member", "id", JobMember.class);
		arp.addMapping("job_member_learningexperiences", "id", JobMemberLearningexperiences.class);
		arp.addMapping("job_member_position", "id", JobMemberPosition.class);
		arp.addMapping("job_member_workexperiences", "id", JobMemberWorkexperiences.class);
		arp.addMapping("job_message_details", "id", JobMessageDetails.class);
		arp.addMapping("job_message_window", "id", JobMessageWindow.class);
		arp.addMapping("job_unit", "id", JobUnit.class);
		arp.addMapping("job_unit_position", "id", JobUnitPosition.class);
		arp.addMapping("wx_msg", "id", WxMsg.class);
	}
}

