package com.admin.web.model;

import com.admin.web.model.base.BaseCity;
import com.jfinal.plugin.activerecord.Page;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class City extends BaseCity<City> {
	public static final City dao = new City().dao();
	public static final String table = "j_city";

    public Page<City> findPage(City info, int pageNumber, int pageSize) {
        String sql = " from " + table + " where 1 = 1 ";
        List<Object> pm = new ArrayList<Object>();

        Page<City> page = dao.paginate(pageNumber, pageSize, "select *", sql, pm.toArray());

        return page;
    }

}
