package com.admin.web.model;

import com.admin.web.model.base.BaseCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class City extends BaseCity<City> {
	public static final City dao = new City().dao();
	public static final String table = "j_city";
}
