package com.admin.web.model;

import com.admin.web.model.base.BaseCompanyInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompanyInfo extends BaseCompanyInfo<CompanyInfo> {
	public static final CompanyInfo dao = new CompanyInfo().dao();
	public static final String table = "j_company_info";
}
