package com.admin.web.model;

import com.admin.web.model.base.BaseCountries;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Countries extends BaseCountries<Countries> {
	public static final Countries dao = new Countries().dao();
	public static final String table = "j_countries";
}
