package com.admin.web.model;

import com.admin.web.model.base.BaseJobInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JobInfo extends BaseJobInfo<JobInfo> {
	public static final JobInfo dao = new JobInfo().dao();
	public static final String table = "j_job_info";
}
