package com.admin.web.model;

import com.admin.web.model.base.BaseJobInfo;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JobInfo extends BaseJobInfo<JobInfo> {
	public static final JobInfo dao = new JobInfo().dao();
	public static final String table = "j_job_info";


    public Page<JobInfo> findPage(JobInfo info, int pageNumber, int pageSize) {
        String sql = " from " + table + " where 1 = 1 ";
        List<Object> pm = new ArrayList<>();
        if (StrKit.notBlank(info.getTitle())) {
            sql += " and instr(title, ?) > 0 ";
            pm.add(info.getTitle());
        }
        if (info.getCityId() != null) {
            sql += " and instr(cityId, ?) > 0 ";
            pm.add(info.getCityId());
        }

        Page<JobInfo> page = dao.paginate(pageNumber, pageSize, "select *", sql, pm.toArray());
        return page;
    }
}
