package com.admin.web.model;

import com.admin.web.model.base.BaseJobMember;

/**
 * 会员信息
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JobMember extends BaseJobMember<JobMember> {
	public static final JobMember dao = new JobMember().dao();
	public static final String table = "job_member";

	public JobMember findByOpenId (String openId){
		return dao.findFirst("select * from " + table + " where openId = ?",openId);
	}
}
