package com.admin.web.model;

import com.admin.web.model.base.BaseJobMemberPosition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JobMemberPosition extends BaseJobMemberPosition<JobMemberPosition> {
	public static final JobMemberPosition dao = new JobMemberPosition().dao();
	public static final String table = "job_member_position";
}
