package com.admin.web.model;

import com.admin.web.model.base.BaseProposal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Proposal extends BaseProposal<Proposal> {
	public static final Proposal dao = new Proposal().dao();
	public static final String table = "j_proposal";
}
