package com.admin.web.model;

import com.admin.web.model.base.BaseSomeone;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Someone extends BaseSomeone<Someone> {
	public static final Someone dao = new Someone().dao();
	public static final String table = "j_someone";
}
