package com.admin.web.model;

import com.admin.web.model.base.BaseUploadFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadFile extends BaseUploadFile<UploadFile> {
	public static final UploadFile dao = new UploadFile().dao();
	public static final String table = "j_upload_file";
}
