package com.admin.web.model;

import com.admin.web.model.base.BaseUserInfo;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfo extends BaseUserInfo<UserInfo> {
	public static final UserInfo dao = new UserInfo().dao();
	public static final String table = "user_info";

    public Page<UserInfo> findPage(UserInfo info, int pageNumber, int pageSize) {
        String sql = " from " + table + " where 1 = 1 ";
        List<Object> pm = new ArrayList<>();
        if (StrKit.notBlank(info.getName())) {
            sql += " and instr(name, ?) > 0 ";
            pm.add(info.getName());
        }


        Page<UserInfo> page = dao.paginate(pageNumber, pageSize, "select *", sql, pm.toArray());
        return page;
    }
}
