package com.admin.web.model;

import com.admin.web.model.base.BaseUserTelExp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserTelExp extends BaseUserTelExp<UserTelExp> {
	public static final UserTelExp dao = new UserTelExp().dao();
	public static final String table = "user_tel_exp";
}
