package com.admin.web.model;

import com.admin.web.model.base.BaseUserCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserCollection extends BaseUserCollection<UserCollection> {
	public static final UserCollection dao = new UserCollection().dao();
	public static final String table = "user_collection";
}
