package com.admin.web.model;

import com.admin.web.model.base.BaseWxMsg;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxMsg extends BaseWxMsg<WxMsg> {
	public static final WxMsg dao = new WxMsg().dao();
	public static final String table = "wx_msg";

	public Page<WxMsg> findPage(int pageNumber, int pageSize) {
		String sql = " from " + table + " where type = '3' ";

		return dao.paginate(pageNumber, pageSize, "select *", sql);
	}

	/**
	 * 通过类型查询 消息
	 * @return
	 */
	public WxMsg findByType(String type) {
		String sql = "select * from " + table + " where type = ? LIMIT 0, 1";

		return dao().findFirst(sql,type);
	}

	/**
	 * 关键字 查询
	 * @return
	 */
	public WxMsg findByKeyWord(String key) {
		String sql = "select * from " + table + " where type = '3' and keyword=? LIMIT 0, 1";

		return dao().findFirst(sql,key);
	}

	/**
	 * 修改 消息
	 */
	public void updateByType(WxMsg wxMsg){
		wxMsg.dao().update();
	}
}
