package com.admin.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJobMessageWindow<M extends BaseJobMessageWindow<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMemberId(java.lang.Integer memberId) {
		set("memberId", memberId);
	}

	public java.lang.Integer getMemberId() {
		return get("memberId");
	}

	public void setMemberName(java.lang.String memberName) {
		set("memberName", memberName);
	}

	public java.lang.String getMemberName() {
		return get("memberName");
	}

	public void setMemberImage(java.lang.String memberImage) {
		set("memberImage", memberImage);
	}

	public java.lang.String getMemberImage() {
		return get("memberImage");
	}

	public void setUnitUserId(java.lang.Integer unitUserId) {
		set("unitUserId", unitUserId);
	}

	public java.lang.Integer getUnitUserId() {
		return get("unitUserId");
	}

	public void setUnitUserName(java.lang.String unitUserName) {
		set("unitUserName", unitUserName);
	}

	public java.lang.String getUnitUserName() {
		return get("unitUserName");
	}

	public void setUnitUserImage(java.lang.String unitUserImage) {
		set("unitUserImage", unitUserImage);
	}

	public java.lang.String getUnitUserImage() {
		return get("unitUserImage");
	}

	public void setUnitPositionId(java.lang.Integer unitPositionId) {
		set("unitPositionId", unitPositionId);
	}

	public java.lang.Integer getUnitPositionId() {
		return get("unitPositionId");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

}
