package com.admin.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUploadFile<M extends BaseUploadFile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setUploadPath(java.lang.String uploadPath) {
		set("uploadPath", uploadPath);
	}

	public java.lang.String getUploadPath() {
		return get("uploadPath");
	}

	public void setUrlPath(java.lang.String urlPath) {
		set("urlPath", urlPath);
	}

	public java.lang.String getUrlPath() {
		return get("urlPath");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

}
