package com.admin.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJobUnitPosition<M extends BaseJobUnitPosition<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMemberId(java.lang.Integer memberId) {
		set("memberId", memberId);
	}

	public java.lang.Integer getMemberId() {
		return get("memberId");
	}

	public void setMemberName(java.lang.String memberName) {
		set("memberName", memberName);
	}

	public java.lang.String getMemberName() {
		return get("memberName");
	}

	public void setMemberImage(java.lang.String memberImage) {
		set("memberImage", memberImage);
	}

	public java.lang.String getMemberImage() {
		return get("memberImage");
	}

	public void setJob(java.lang.String job) {
		set("job", job);
	}

	public java.lang.String getJob() {
		return get("job");
	}

	public void setSalary(java.lang.String salary) {
		set("salary", salary);
	}

	public java.lang.String getSalary() {
		return get("salary");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public void setUnitId(java.lang.Integer unitId) {
		set("unitId", unitId);
	}

	public java.lang.Integer getUnitId() {
		return get("unitId");
	}

	public void setCountry(java.lang.String country) {
		set("country", country);
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setDutyDetails(java.lang.String dutyDetails) {
		set("dutyDetails", dutyDetails);
	}

	public java.lang.String getDutyDetails() {
		return get("dutyDetails");
	}

	public void setSkill(java.lang.String skill) {
		set("skill", skill);
	}

	public java.lang.String getSkill() {
		return get("skill");
	}

	public void setStreet(java.lang.String street) {
		set("street", street);
	}

	public java.lang.String getStreet() {
		return get("street");
	}

	public void setJobDetail(java.lang.String jobDetail) {
		set("jobDetail", jobDetail);
	}

	public java.lang.String getJobDetail() {
		return get("jobDetail");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setQualification(java.lang.String qualification) {
		set("qualification", qualification);
	}

	public java.lang.String getQualification() {
		return get("qualification");
	}

	public void setStrength(java.lang.String strength) {
		set("strength", strength);
	}

	public java.lang.String getStrength() {
		return get("strength");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

}
