package com.admin.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxMsg<M extends BaseWxMsg<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setMsgType(java.lang.String msgType) {
		set("msgType", msgType);
	}

	public java.lang.String getMsgType() {
		return get("msgType");
	}

	public void setText(java.lang.String text) {
		set("text", text);
	}

	public java.lang.String getText() {
		return get("text");
	}

	public void setNewTitle(java.lang.String newTitle) {
		set("newTitle", newTitle);
	}

	public java.lang.String getNewTitle() {
		return get("newTitle");
	}

	public void setNewUrl(java.lang.String newUrl) {
		set("newUrl", newUrl);
	}

	public java.lang.String getNewUrl() {
		return get("newUrl");
	}

	public void setNewDescription(java.lang.String newDescription) {
		set("newDescription", newDescription);
	}

	public java.lang.String getNewDescription() {
		return get("newDescription");
	}

	public void setNewPicUrl(java.lang.String newPicUrl) {
		set("newPicUrl", newPicUrl);
	}

	public java.lang.String getNewPicUrl() {
		return get("newPicUrl");
	}

	public void setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
	}

	public java.lang.String getKeyword() {
		return get("keyword");
	}

}
