package com.admin.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJobInfo<M extends BaseJobInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setCompanyId(java.lang.Integer companyId) {
		set("companyId", companyId);
	}

	public java.lang.Integer getCompanyId() {
		return get("companyId");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("companyName", companyName);
	}

	public java.lang.String getCompanyName() {
		return get("companyName");
	}

	public void setCompanyLogo(java.lang.String companyLogo) {
		set("companyLogo", companyLogo);
	}

	public java.lang.String getCompanyLogo() {
		return get("companyLogo");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setCountriesId(java.lang.Integer countriesId) {
		set("countriesId", countriesId);
	}

	public java.lang.Integer getCountriesId() {
		return get("countriesId");
	}

	public void setCountriesName(java.lang.String countriesName) {
		set("countriesName", countriesName);
	}

	public java.lang.String getCountriesName() {
		return get("countriesName");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("cityId", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("cityId");
	}

	public void setCityName(java.lang.String cityName) {
		set("cityName", cityName);
	}

	public java.lang.String getCityName() {
		return get("cityName");
	}

	public void setJobTypeName(java.lang.Integer jobTypeName) {
		set("jobTypeName", jobTypeName);
	}

	public java.lang.Integer getJobTypeName() {
		return get("jobTypeName");
	}

	public void setJobTypeValue(java.lang.String jobTypeValue) {
		set("jobTypeValue", jobTypeValue);
	}

	public java.lang.String getJobTypeValue() {
		return get("jobTypeValue");
	}

	public void setJobNatureName(java.lang.Integer jobNatureName) {
		set("jobNatureName", jobNatureName);
	}

	public java.lang.Integer getJobNatureName() {
		return get("jobNatureName");
	}

	public void setJobNatureValue(java.lang.String jobNatureValue) {
		set("jobNatureValue", jobNatureValue);
	}

	public java.lang.String getJobNatureValue() {
		return get("jobNatureValue");
	}

	public void setJobWelfareName(java.lang.Integer jobWelfareName) {
		set("jobWelfareName", jobWelfareName);
	}

	public java.lang.Integer getJobWelfareName() {
		return get("jobWelfareName");
	}

	public void setJobWelfareValue(java.lang.String jobWelfareValue) {
		set("jobWelfareValue", jobWelfareValue);
	}

	public java.lang.String getJobWelfareValue() {
		return get("jobWelfareValue");
	}

	public void setJobSalaryName(java.lang.Integer jobSalaryName) {
		set("jobSalaryName", jobSalaryName);
	}

	public java.lang.Integer getJobSalaryName() {
		return get("jobSalaryName");
	}

	public void setJobSalaryValue(java.lang.String jobSalaryValue) {
		set("jobSalaryValue", jobSalaryValue);
	}

	public java.lang.String getJobSalaryValue() {
		return get("jobSalaryValue");
	}

	public void setJobRequirementsName(java.lang.Integer jobRequirementsName) {
		set("jobRequirementsName", jobRequirementsName);
	}

	public java.lang.Integer getJobRequirementsName() {
		return get("jobRequirementsName");
	}

	public void setJobRequirementsValue(java.lang.String jobRequirementsValue) {
		set("jobRequirementsValue", jobRequirementsValue);
	}

	public java.lang.String getJobRequirementsValue() {
		return get("jobRequirementsValue");
	}

	public void setDetails(java.lang.String details) {
		set("details", details);
	}

	public java.lang.String getDetails() {
		return get("details");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

}
