package com.admin.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJobMember<M extends BaseJobMember<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setBirthday(java.lang.String birthday) {
		set("birthday", birthday);
	}

	public java.lang.String getBirthday() {
		return get("birthday");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setMobileCode(java.lang.String mobileCode) {
		set("mobileCode", mobileCode);
	}

	public java.lang.String getMobileCode() {
		return get("mobileCode");
	}

	public void setRole(java.lang.String role) {
		set("role", role);
	}

	public java.lang.String getRole() {
		return get("role");
	}

	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}

	public java.lang.String getOpenId() {
		return get("openId");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setLanguage(java.lang.String language) {
		set("language", language);
	}

	public java.lang.String getLanguage() {
		return get("language");
	}

	public void setCountry(java.lang.String country) {
		set("country", country);
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setLoginDate(java.util.Date loginDate) {
		set("loginDate", loginDate);
	}

	public java.util.Date getLoginDate() {
		return get("loginDate");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}

	public java.lang.String getImage() {
		return get("image");
	}

	public void setUnitId(java.lang.Integer unitId) {
		set("unitId", unitId);
	}

	public java.lang.Integer getUnitId() {
		return get("unitId");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public void setJobStatus(java.lang.String jobStatus) {
		set("jobStatus", jobStatus);
	}

	public java.lang.String getJobStatus() {
		return get("jobStatus");
	}

	public void setBeginWork(java.lang.String beginWork) {
		set("beginWork", beginWork);
	}

	public java.lang.String getBeginWork() {
		return get("beginWork");
	}

	public void setResidencePermit(java.lang.String residencePermit) {
		set("residencePermit", residencePermit);
	}

	public java.lang.String getResidencePermit() {
		return get("residencePermit");
	}

	public void setBranchOfWork(java.lang.String branchOfWork) {
		set("branchOfWork", branchOfWork);
	}

	public java.lang.String getBranchOfWork() {
		return get("branchOfWork");
	}

}
