package com.admin.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserCompany<M extends BaseUserCompany<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setUserId(Integer userId) {
		set("userId", userId);
	}

	public Integer getUserId() {
		return get("userId");
	}

	public void setUserName(String userName) {
		set("userName", userName);
	}

	public String getUserName() {
		return get("userName");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setPublicity(String publicity) {
		set("publicity", publicity);
	}

	public String getPublicity() {
		return get("publicity");
	}

	public void setQRCode(String QRCode) {
		set("QRCode", QRCode);
	}

	public String getQRCode() {
		return get("QRCode");
	}

	public void setInfo(String info) {
		set("info", info);
	}

	public String getInfo() {
		return get("info");
	}

	public void setLogo(String logo) {
		set("logo", logo);
	}

	public String getLogo() {
		return get("logo");
	}

}
