package com.admin.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJobMemberWorkexperiences<M extends BaseJobMemberWorkexperiences<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMemberId(java.lang.Integer memberId) {
		set("memberId", memberId);
	}

	public java.lang.Integer getMemberId() {
		return get("memberId");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public void setPositon(java.lang.String positon) {
		set("positon", positon);
	}

	public java.lang.String getPositon() {
		return get("positon");
	}

	public void setJobContent(java.lang.String jobContent) {
		set("jobContent", jobContent);
	}

	public java.lang.String getJobContent() {
		return get("jobContent");
	}

	public void setWorkStart(java.lang.String workStart) {
		set("workStart", workStart);
	}

	public java.lang.String getWorkStart() {
		return get("workStart");
	}

	public void setWorkEnd(java.lang.String workEnd) {
		set("workEnd", workEnd);
	}

	public java.lang.String getWorkEnd() {
		return get("workEnd");
	}

}
