package com.admin.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSomeone<M extends BaseSomeone<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCountriesId(java.lang.Integer countriesId) {
		set("countriesId", countriesId);
	}

	public java.lang.Integer getCountriesId() {
		return get("countriesId");
	}

	public void setCountriesName(java.lang.String countriesName) {
		set("countriesName", countriesName);
	}

	public java.lang.String getCountriesName() {
		return get("countriesName");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("cityId", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("cityId");
	}

	public void setCityName(java.lang.String cityName) {
		set("cityName", cityName);
	}

	public java.lang.String getCityName() {
		return get("cityName");
	}

	public void setSomeoneTypeId(java.lang.Integer someoneTypeId) {
		set("someoneTypeId", someoneTypeId);
	}

	public java.lang.Integer getSomeoneTypeId() {
		return get("someoneTypeId");
	}

	public void setSomeoneTypeValue(java.lang.String someoneTypeValue) {
		set("someoneTypeValue", someoneTypeValue);
	}

	public java.lang.String getSomeoneTypeValue() {
		return get("someoneTypeValue");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setDetails(java.lang.String details) {
		set("details", details);
	}

	public java.lang.String getDetails() {
		return get("details");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

}
