package com.admin.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJobMemberLearningexperiences<M extends BaseJobMemberLearningexperiences<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMemberId(java.lang.Integer memberId) {
		set("memberId", memberId);
	}

	public java.lang.Integer getMemberId() {
		return get("memberId");
	}

	public void setSchool(java.lang.String school) {
		set("school", school);
	}

	public java.lang.String getSchool() {
		return get("school");
	}

	public void setSpecialty(java.lang.String specialty) {
		set("specialty", specialty);
	}

	public java.lang.String getSpecialty() {
		return get("specialty");
	}

	public void setQualification(java.lang.String qualification) {
		set("qualification", qualification);
	}

	public java.lang.String getQualification() {
		return get("qualification");
	}

	public void setLearingStart(java.lang.String learingStart) {
		set("learingStart", learingStart);
	}

	public java.lang.String getLearingStart() {
		return get("learingStart");
	}

	public void setLearnEnd(java.lang.String learnEnd) {
		set("learnEnd", learnEnd);
	}

	public java.lang.String getLearnEnd() {
		return get("learnEnd");
	}

	public void setLearningExperience(java.lang.String learningExperience) {
		set("learningExperience", learningExperience);
	}

	public java.lang.String getLearningExperience() {
		return get("learningExperience");
	}

}
